const JOBS_KEY="skillora_jobs", PROPOSALS_KEY="skillora_proposals", SAVED_KEY="skillora_saved_jobs";
const seedJobs=[
{id:"job-1001",title:"Build a responsive React dashboard",category:"Web Development",description:"Create a modern responsive admin dashboard with React, reusable components, charts, authentication screens and clean API integration.",skills:["React","JavaScript","CSS","REST API"],budget:850,experience:"Intermediate",duration:"2-4 weeks",client:"Nova Labs",rating:4.9,proposals:7,createdAt:Date.now()-86400000*2},
{id:"job-1002",title:"UI/UX designer for SaaS landing page",category:"UI/UX Design",description:"Design a conversion-focused SaaS landing page in Figma with desktop and mobile variants, a small design system and developer handoff.",skills:["Figma","UI Design","UX","Prototyping"],budget:450,experience:"Intermediate",duration:"1-2 weeks",client:"Orbit Cloud",rating:4.8,proposals:12,createdAt:Date.now()-86400000*4},
{id:"job-1003",title:"SEO content strategy and blog writing",category:"Writing",description:"Develop an SEO content plan and write 8 high-quality articles targeting commercial and informational keywords.",skills:["SEO","Content Writing","Keyword Research"],budget:600,experience:"Expert",duration:"2-3 weeks",client:"MarketPro",rating:4.7,proposals:15,createdAt:Date.now()-86400000*1},
{id:"job-1004",title:"Short-form video editor for social media",category:"Video Editing",description:"Edit 20 vertical videos for TikTok, Reels and Shorts with captions, cuts, transitions and platform-ready exports.",skills:["Premiere Pro","CapCut","After Effects"],budget:500,experience:"Intermediate",duration:"1-2 weeks",client:"Creator House",rating:5,proposals:9,createdAt:Date.now()-86400000*3},
{id:"job-1005",title:"Node.js API development",category:"Web Development",description:"Build secure REST endpoints, validation, authentication and database integrations for an existing Node.js application.",skills:["Node.js","Express","MongoDB","API"],budget:1100,experience:"Expert",duration:"3-5 weeks",client:"FinStack",rating:4.9,proposals:5,createdAt:Date.now()-86400000*7},
{id:"job-1006",title:"Social media campaign setup",category:"Digital Marketing",description:"Plan and launch a two-week paid social campaign including audiences, creatives, tracking and performance reporting.",skills:["Meta Ads","Analytics","Marketing"],budget:700,experience:"Intermediate",duration:"2 weeks",client:"Growthly",rating:4.6,proposals:18,createdAt:Date.now()-86400000*5}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function getJobs(){let j=read(JOBS_KEY,null);if(!j){write(JOBS_KEY,seedJobs);return seedJobs}return j}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function money(v){return "$"+Number(v||0).toLocaleString()}
function toast(m){let t=$("#toast");if(!t){t=document.createElement("div");t.id="toast";t.className="job-toast";document.body.append(t)}t.textContent=m;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2400)}
function nav(){const b=$("#jobMenu"),m=$("#jobMobile");if(b&&m)b.onclick=()=>m.classList.toggle("open")}
function card(j){return `<article class="job-card"><div class="job-card-top"><div class="job-logo">${esc(j.category.slice(0,2).toUpperCase())}</div><button class="icon-btn save-job" data-id="${j.id}" aria-label="Save job">♡</button></div><span class="job-category">${esc(j.category)}</span><h3>${esc(j.title)}</h3><p>${esc(j.description)}</p><div class="skill-list">${j.skills.map(s=>`<span>${esc(s)}</span>`).join("")}</div><div class="job-meta"><span>◷ ${esc(j.duration)}</span><span>★ ${j.rating}</span><span>${j.proposals} proposals</span></div><div class="job-card-bottom"><strong>${money(j.budget)}</strong><a class="primary-btn small" href="job-details.html?id=${encodeURIComponent(j.id)}">View Details</a></div></article>`}
function setupFind(){let grid=$("#jobGrid");if(!grid)return;let jobs=getJobs();const render=()=>{grid.innerHTML='<div class="loading-state">Loading jobs…</div>';setTimeout(()=>{try{let q=$("#jobSearch").value.toLowerCase().trim(),cat=$("#jobCategory").value,budget=Number($("#jobBudget").value)||Infinity,exp=$("#jobExperience").value,sort=$("#jobSort").value;let r=jobs.filter(j=>(!q||[j.title,j.description,j.category,...j.skills].join(" ").toLowerCase().includes(q))&&(!cat||j.category===cat)&&j.budget<=budget&&(!exp||j.experience===exp));r.sort((a,b)=>sort==="budget-low"?a.budget-b.budget:sort==="budget-high"?b.budget-a.budget:b.createdAt-a.createdAt);$("#resultCount").textContent=`${r.length} job${r.length!==1?"s":""} found`;grid.innerHTML=r.length?r.map(card).join(""):'<div class="empty-state"><div>⌕</div><h3>No jobs found</h3><p>Try changing your search or filters.</p></div>';$$(".save-job").forEach(x=>x.onclick=()=>{let s=read(SAVED_KEY,[]),id=x.dataset.id;s=s.includes(id)?s.filter(v=>v!==id):[...s,id];write(SAVED_KEY,s);x.textContent=s.includes(id)?"♥":"♡";toast(s.includes(id)?"Job saved":"Job removed from saved")})}catch(e){console.error(e)}},250)};["jobSearch","jobCategory","jobBudget","jobExperience","jobSort"].forEach(id=>$("#"+id)?.addEventListener("input",render));$("#clearFilters")?.addEventListener("click",()=>{$("#jobSearch").value="";$("#jobCategory").value="";$("#jobBudget").value="";$("#jobExperience").value="";render()});render()}
function setupDetails(){let box=$("#jobDetails");if(!box)return;let id=new URLSearchParams(location.search).get("id"),j=getJobs().find(x=>x.id===id)||getJobs()[0];if(!j){box.innerHTML='<div class="empty-state">Job not found.</div>';return}document.title=j.title+" — Skillora";box.innerHTML=`<div class="details-head"><div><span class="job-category">${esc(j.category)}</span><h1>${esc(j.title)}</h1><p>Posted by <strong>${esc(j.client)}</strong> · ★ ${j.rating}</p></div><button class="secondary-btn" id="saveDetail">♡ Save Job</button></div><div class="details-layout"><main class="details-main"><h2>About the job</h2><p>${esc(j.description)}</p><h2>Required skills</h2><div class="skill-list">${j.skills.map(s=>`<span>${esc(s)}</span>`).join("")}</div><h2>Project information</h2><div class="info-grid"><div><small>Budget</small><strong>${money(j.budget)}</strong></div><div><small>Experience</small><strong>${esc(j.experience)}</strong></div><div><small>Duration</small><strong>${esc(j.duration)}</strong></div><div><small>Proposals</small><strong>${j.proposals}</strong></div></div></main><aside class="apply-card"><h3>Ready to apply?</h3><p>Send a tailored proposal and introduce your approach.</p><a class="primary-btn" href="submit-proposal.html?id=${encodeURIComponent(j.id)}">Submit Proposal</a><a class="text-link" href="find-jobs.html">← Back to jobs</a></aside></div>`;$("#saveDetail").onclick=()=>{let s=read(SAVED_KEY,[]);s=s.includes(j.id)?s.filter(v=>v!==j.id):[...s,j.id];write(SAVED_KEY,s);$("#saveDetail").textContent=s.includes(j.id)?"♥ Saved":"♡ Save Job"}}
function setupPost(){let f=$("#postJobForm");if(!f)return;f.onsubmit=e=>{e.preventDefault();let data=Object.fromEntries(new FormData(f));if(!data.title||!data.category||!data.description||!data.budget){$("#formError").textContent="Please complete all required fields.";return}let jobs=getJobs();jobs.unshift({id:"job-"+Date.now(),title:data.title,category:data.category,description:data.description,skills:data.skills.split(",").map(x=>x.trim()).filter(Boolean),budget:Number(data.budget),experience:data.experience,duration:data.duration,client:"You",rating:5,proposals:0,createdAt:Date.now()});write(JOBS_KEY,jobs);$("#formError").textContent="";toast("Job posted successfully");setTimeout(()=>location.href="find-jobs.html",500)}}
function setupProposal(){let f=$("#proposalForm");if(!f)return;let j=getJobs().find(x=>x.id===new URLSearchParams(location.search).get("id"))||getJobs()[0];$("#proposalJob").innerHTML=`<strong>${esc(j.title)}</strong><span>${money(j.budget)} · ${esc(j.client)}</span>`;f.onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(f)),ps=read(PROPOSALS_KEY,[]);if(!d.cover||!d.bid||!d.days){$("#formError").textContent="Complete all proposal fields.";return}if(ps.some(p=>p.jobId===j.id)){$("#formError").textContent="You already submitted a proposal for this job.";return}ps.unshift({id:"prop-"+Date.now(),jobId:j.id,title:j.title,bid:Number(d.bid),days:Number(d.days),cover:d.cover,status:"Pending",createdAt:Date.now()});write(PROPOSALS_KEY,ps);write(JOBS_KEY,getJobs().map(x=>x.id===j.id?{...x,proposals:x.proposals+1}:x));toast("Proposal submitted");setTimeout(()=>location.href="my-proposals.html",500)}}
function setupProposals(){let grid=$("#proposalGrid");if(!grid)return;let ps=read(PROPOSALS_KEY,[]);const render=()=>{let q=$("#proposalSearch").value.toLowerCase(),st=$("#proposalStatus").value,sort=$("#proposalSort").value,r=ps.filter(p=>(!q||p.title.toLowerCase().includes(q))&&(!st||p.status===st));r.sort((a,b)=>sort==="bid-high"?b.bid-a.bid:b.createdAt-a.createdAt);$("#proposalStats").innerHTML=`<div><strong>${ps.length}</strong><span>Total</span></div><div><strong>${ps.filter(p=>p.status==="Pending").length}</strong><span>Pending</span></div><div><strong>${ps.filter(p=>p.status==="Accepted").length}</strong><span>Accepted</span></div><div><strong>${ps.filter(p=>p.status==="Rejected").length}</strong><span>Rejected</span></div>`;grid.innerHTML=r.length?r.map(p=>`<article class="proposal-card"><div><span class="status ${p.status.toLowerCase()}">${p.status}</span><h3>${esc(p.title)}</h3><p>${esc(p.cover)}</p></div><div class="proposal-side"><strong>${money(p.bid)}</strong><span>${p.days} days</span><small>${new Date(p.createdAt).toLocaleDateString()}</small></div></article>`).join(""):'<div class="empty-state"><h3>No proposals yet</h3><p>Submit your first proposal from a job details page.</p></div>'};["proposalSearch","proposalStatus","proposalSort"].forEach(id=>$("#"+id)?.addEventListener("input",render));render()}
document.addEventListener("DOMContentLoaded",()=>{nav();setupFind();setupDetails();setupPost();setupProposal();setupProposals()});
