(() => {
"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const FAV_KEY="skillora_favorites_v7", PROFILE_KEY="skillora_profile", SERVICES_KEY="skillora_services", JOBS_KEY="skillora_jobs";
const categories=["Web Development","Graphic Design","Mobile Development","Data Analysis","Digital Marketing","Content Writing","UI/UX Design","Video Editing","Writing"];
const people=[
{id:"alex",type:"freelancer",name:"Alex Johnson",title:"Senior Full Stack Developer",category:"Web Development",price:50,rating:4.9,reviews:128,popularity:980,experience:"Expert",delivery:7,image:"https://i.pravatar.cc/300?img=12",skills:["React","Node.js","TypeScript","Next.js"],description:"Scalable full-stack web applications with modern architecture and clean APIs."},
{id:"sophia",type:"freelancer",name:"Sophia Martinez",title:"Senior UI/UX Designer",category:"UI/UX Design",price:40,rating:4.9,reviews:96,popularity:820,experience:"Expert",delivery:7,image:"https://i.pravatar.cc/300?img=47",skills:["Figma","UI Design","UX Research","Prototyping"],description:"Research-driven interfaces, design systems and conversion-focused product experiences."},
{id:"david",type:"freelancer",name:"David Wilson",title:"Mobile App Developer",category:"Mobile Development",price:45,rating:4.8,reviews:74,popularity:650,experience:"Expert",delivery:14,image:"https://i.pravatar.cc/300?img=13",skills:["Flutter","React Native","iOS","Android"],description:"High-performance cross-platform mobile applications built for real-world products."},
{id:"emma",type:"freelancer",name:"Emma Chen",title:"Professional Graphic Designer",category:"Graphic Design",price:35,rating:4.9,reviews:112,popularity:760,experience:"Expert",delivery:5,image:"https://i.pravatar.cc/300?img=44",skills:["Photoshop","Illustrator","Branding","Logo Design"],description:"Complete brand identities, marketing graphics and memorable visual systems."},
{id:"olivia",type:"freelancer",name:"Olivia Brown",title:"SEO Content Writer",category:"Content Writing",price:30,rating:4.9,reviews:86,popularity:710,experience:"Intermediate",delivery:4,image:"https://i.pravatar.cc/300?img=49",skills:["SEO","Copywriting","Blog Writing","Research"],description:"SEO content that targets intent, builds authority and converts readers."},
{id:"liam",type:"freelancer",name:"Liam Anderson",title:"DevOps & Cloud Engineer",category:"Web Development",price:55,rating:4.8,reviews:59,popularity:590,experience:"Expert",delivery:10,image:"https://i.pravatar.cc/300?img=68",skills:["AWS","Docker","Kubernetes","Terraform"],description:"Cloud infrastructure, CI/CD and deployment automation for growing products."}
];
const seededServices=[
{id:"svc-v7-1",type:"service",name:"Alex Johnson",title:"I will build a production-ready React web application",category:"Web Development",price:120,rating:4.9,reviews:128,popularity:990,experience:"Expert",delivery:7,image:"https://picsum.photos/seed/react-market/700/450",skills:["React","Node.js","TypeScript"],description:"Modern responsive web app with reusable components, API integration and deployment guidance.",createdAt:Date.now()-86400000*3},
{id:"svc-v7-2",type:"service",name:"Sophia Martinez",title:"I will design a premium SaaS UI/UX in Figma",category:"UI/UX Design",price:90,rating:4.9,reviews:96,popularity:900,experience:"Expert",delivery:7,image:"https://picsum.photos/seed/uiux-market/700/450",skills:["Figma","UI","UX","Prototype"],description:"High-fidelity screens, responsive variants and developer-ready design system.",createdAt:Date.now()-86400000*5},
{id:"svc-v7-3",type:"service",name:"Olivia Brown",title:"I will write SEO blog content that ranks",category:"Content Writing",price:45,rating:4.9,reviews:86,popularity:760,experience:"Intermediate",delivery:4,image:"https://picsum.photos/seed/seo-market/700/450",skills:["SEO","Writing","Research"],description:"Search-intent driven articles with keyword research, structure and optimization.",createdAt:Date.now()-86400000*1},
{id:"svc-v7-4",type:"service",name:"Emma Chen",title:"I will create your complete brand identity",category:"Graphic Design",price:75,rating:4.9,reviews:112,popularity:810,experience:"Expert",delivery:5,image:"https://picsum.photos/seed/brand-market/700/450",skills:["Branding","Logo","Illustrator"],description:"Logo, colors, typography and brand guidelines for a consistent visual identity.",createdAt:Date.now()-86400000*8},
{id:"svc-v7-5",type:"service",name:"Liam Anderson",title:"I will configure AWS cloud and DevOps pipelines",category:"Web Development",price:150,rating:4.8,reviews:59,popularity:640,experience:"Expert",delivery:10,image:"https://picsum.photos/seed/aws-market/700/450",skills:["AWS","Docker","Terraform"],description:"Production-ready cloud infrastructure with CI/CD and deployment automation.",createdAt:Date.now()-86400000*2}
];
const fallbackJobs=[
{id:"job-v7-1",type:"job",name:"Nova Labs",title:"Build a responsive React dashboard",category:"Web Development",price:850,rating:4.9,reviews:7,popularity:700,experience:"Intermediate",delivery:28,image:"https://picsum.photos/seed/job-react/700/450",description:"Create a modern responsive admin dashboard with React, charts and authentication.",createdAt:Date.now()-86400000*2},
{id:"job-v7-2",type:"job",name:"Orbit Cloud",title:"UI/UX designer for SaaS landing page",category:"UI/UX Design",price:450,rating:4.8,reviews:12,popularity:620,experience:"Intermediate",delivery:14,image:"https://picsum.photos/seed/job-ui/700/450",description:"Design a conversion-focused SaaS landing page in Figma with desktop and mobile variants.",createdAt:Date.now()-86400000*4},
{id:"job-v7-3",type:"job",name:"Growth Studio",title:"SEO content strategy and blog writing",category:"Content Writing",price:650,rating:4.7,reviews:9,popularity:540,experience:"Intermediate",delivery:21,image:"https://picsum.photos/seed/job-seo/700/450",description:"Build an SEO content plan and write eight commercial and informational articles.",createdAt:Date.now()-86400000*6}
];
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const getFav=()=>{try{return JSON.parse(localStorage.getItem(FAV_KEY))||[]}catch{return[]}};
const setFav=v=>localStorage.setItem(FAV_KEY,JSON.stringify(v));
const getServices=()=>{try{return JSON.parse(localStorage.getItem(SERVICES_KEY))||[]}catch{return[]}};
const getJobs=()=>{try{return JSON.parse(localStorage.getItem(JOBS_KEY))||[]}catch{return[]}};
let allData=[], filtered=[], page=1, pageSize=6, timer;
function normalize(){
 const custom=getServices().map((s,i)=>({...s,type:"service",name:s.seller||"Hasaan Ali",title:s.title,price:+s.price||0,rating:+s.rating||4.7,reviews:+s.reviews||18,popularity:+s.popularity||100,experience:s.experience||"Intermediate",delivery:parseInt(s.delivery)||7,image:s.image||"https://picsum.photos/seed/custom"+i+"/700/450",createdAt:s.createdAt||Date.now()}));
 const jobs=(getJobs().length?getJobs():fallbackJobs).map(j=>({...j,type:"job",name:j.client||j.name||"Client",title:j.title,price:+j.budget||+j.price||0,rating:+j.rating||4.7,reviews:+j.proposals||j.reviews||0,popularity:+j.proposals*20||j.popularity||100,experience:j.experience||"Intermediate",delivery:parseInt(j.duration)||j.delivery||14,image:j.image||"https://picsum.photos/seed/job"+j.id+"/700/450",createdAt:j.createdAt||Date.now()}));
 const fre=people;
 allData=[...seededServices,...custom,...fre,...jobs];
 const seen=new Set(); allData=allData.filter(x=>{if(seen.has(x.id))return false;seen.add(x.id);return true});
}
function populateCategories(){const s=$("#categoryFilter"); categories.concat(allData.map(x=>x.category)).filter((v,i,a)=>v&&a.indexOf(v)===i).sort().forEach(c=>s.insertAdjacentHTML("beforeend",`<option value="${esc(c)}">${esc(c)}</option>`));}
function readState(){return{q:$("#marketSearch").value.trim().toLowerCase(),cat:$("#categoryFilter").value,min:+$("#minPrice").value||0,max:+$("#maxPrice").value||Infinity,rating:+($('input[name="rating"]:checked')?.value||0),delivery:+$("#deliveryFilter").value||Infinity,experience:$("#experienceFilter").value,types:$('input[name="type"]:checked')?$$('input[name="type"]:checked').map(x=>x.value):[],sort:$("#sortSelect").value};}
function matches(x,s){const hay=[x.title,x.name,x.category,x.description,...(x.skills||[])].join(" ").toLowerCase();return(!s.q||hay.includes(s.q))&&(!s.cat||x.category===s.cat)&&x.price>=s.min&&x.price<=s.max&&x.rating>=s.rating&&x.delivery<=s.delivery&&(!s.experience||x.experience===s.experience)&&s.types.includes(x.type);}
function score(x,s){if(!s.q)return 0;const q=s.q, hay=(x.title+" "+x.category+" "+x.name+" "+(x.skills||[]).join(" ")).toLowerCase();return (hay.startsWith(q)?30:0)+(x.title.toLowerCase().includes(q)?20:0)+(x.category.toLowerCase().includes(q)?15:0)+(x.skills||[]).some(k=>k.toLowerCase().includes(q))?10:0;}
function sortItems(a,b,s){switch(s.sort){case"price-asc":return a.price-b.price;case"price-desc":return b.price-a.price;case"rating":return b.rating-a.rating||b.reviews-a.reviews;case"popular":return b.popularity-a.popularity;case"newest":return b.createdAt-a.createdAt;default:return score(b,s)-score(a,s)||b.popularity-a.popularity;}}
function card(x){
 const fav=getFav().includes(x.id), type=x.type==="service"?"Service":x.type==="freelancer"?"Freelancer":"Job";
 const href=x.type==="service"?`service-details.html?id=${encodeURIComponent(x.id)}`:x.type==="freelancer"?`freelancer-profile.html?id=${encodeURIComponent(x.id)}`:`job-details.html?id=${encodeURIComponent(x.id)}`;
 return `<article class="market-card"><div class="card-image"><img src="${esc(x.image)}" alt="${esc(x.title)}" loading="lazy"><span class="type-badge">${type}</span><button class="save-btn ${fav?"saved":""}" data-fav="${esc(x.id)}" aria-label="${fav?"Remove from favorites":"Save to favorites"}"><i class="${fav?"fa-solid":"fa-regular"} fa-heart"></i></button></div><div class="card-body"><div class="card-top"><span>${esc(x.category)}</span><span class="rating"><i class="fa-solid fa-star"></i> ${x.rating.toFixed(1)} <small>(${x.reviews})</small></span></div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="skill-row">${(x.skills||[]).slice(0,3).map(k=>`<span>${esc(k)}</span>`).join("")}</div><div class="seller-row"><img src="${esc(x.image)}" alt=""><div><strong>${esc(x.name)}</strong><small>${esc(x.experience)} • ${x.delivery} day${x.delivery===1?"":"s"}</small></div><strong class="price">${x.type==="job"?"Budget":"From"} $${x.price.toLocaleString()}</strong></div><a class="card-link" href="${href}">View details <i class="fa-solid fa-arrow-right"></i></a></div></article>`;
}
function render(){
 const s=readState();filtered=allData.filter(x=>matches(x,s)).sort((a,b)=>sortItems(a,b,s));const pages=Math.max(1,Math.ceil(filtered.length/pageSize));page=Math.min(page,pages);
 $("#resultsMeta").textContent=`${filtered.length} result${filtered.length===1?"":"s"} • ${s.q?"Search: "+$("#marketSearch").value:"All marketplace listings"}`;
 $("#loadingState").classList.add("hidden");$("#emptyState").classList.toggle("hidden",filtered.length>0);$("#resultsGrid").innerHTML=filtered.slice((page-1)*pageSize,page*pageSize).map(card).join("");
 renderActive(s);renderPagination(pages);bindFavs();
}
function renderActive(s){const labels=[];if(s.q)labels.push(`Search: ${esc($("#marketSearch").value)}`);if(s.cat)labels.push(s.cat);if(s.rating)labels.push(`${s.rating}+ ★`);if(s.delivery<Infinity)labels.push(`≤ ${s.delivery} days`);if(s.experience)labels.push(s.experience);if(s.min||s.max<1500)labels.push(`$${s.min}–$${s.max}`);$("#activeFilters").innerHTML=labels.map(l=>`<span>${l}</span>`).join("");}
function renderPagination(pages){$("#pagination").innerHTML=pages<=1?"":Array.from({length:pages},(_,i)=>`<button class="${i+1===page?"active":""}" data-page="${i+1}">${i+1}</button>`).join("");$$("[data-page]").forEach(b=>b.onclick=()=>{page=+b.dataset.page;render();window.scrollTo({top:500,behavior:"smooth"})});}
function bindFavs(){$$("[data-fav]").forEach(b=>b.onclick=()=>{const id=b.dataset.fav,f=getFav(),has=f.includes(id);setFav(has?f.filter(x=>x!==id):[...f,id]);toast(has?"Removed from favorites":"Saved to My Favorites");render()});}
function toast(msg){const t=$("#toast");t.querySelector("span").textContent=msg;t.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>t.classList.remove("show"),2200)}
function reset(){ $("#marketSearch").value="";$("#categoryFilter").value="";$("#minPrice").value=0;$("#maxPrice").value=1500;$("#deliveryFilter").value="";$("#experienceFilter").value="";$('input[name="rating"][value="0"]').checked=true;$$('input[name="type"]').forEach(x=>x.checked=true);$("#sortSelect").value="relevance";page=1;render();}
function bind(){const rerender=()=>{page=1;render()};$("#searchButton").onclick=rerender;$("#marketSearch").oninput=()=>{clearTimeout(timer);timer=setTimeout(rerender,220)};$("#clearSearch").onclick=()=>{$("#marketSearch").value="";rerender()};$$(".quick-chips button").forEach(b=>b.onclick=()=>{$("#marketSearch").value=b.dataset.query;rerender()});["categoryFilter","deliveryFilter","experienceFilter","sortSelect","minPrice","maxPrice"].forEach(id=>$("#"+id).addEventListener("change",rerender));$$('input[name="rating"],input[name="type"]').forEach(x=>x.addEventListener("change",rerender));$("#resetFilters").onclick=reset;$("#emptyReset").onclick=reset;$("#filterToggle").onclick=()=>$("#filterPanel").classList.add("open");$("#closeFilters").onclick=()=>$("#filterPanel").classList.remove("open");}
function init(){const params=new URLSearchParams(location.search);normalize();populateCategories();bind();if(params.get("q")){$("#marketSearch").value=params.get("q")}if(params.get("favorites")==="1"){allData=allData.filter(x=>getFav().includes(x.id));}render();}
document.addEventListener("DOMContentLoaded",init);
})();